spring:
  application:
    name: authentication-service
  security:
    user:
      name: subhash
      password: subhash
server:
  port: 8484
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/


